# Netlify configuration for PUO Memo landing page

[build]
  # Directory to change to before starting build
  base = "/"
  
  # Directory that contains the deploy-ready files
  publish = "landing/"
  
  # Build command (if you have a build step)
  # command = "npm run build"

# Redirects for API
[[redirects]]
  from = "/api/*"
  to = "https://api.puo-memo.com/api/:splat"
  status = 200
  force = true

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Custom domain redirect (when you set it up)
# [[redirects]]
#   from = "https://fancy-dango-fe613b.netlify.app/*"
#   to = "https://puo-memo.com/:splat"
#   status = 301
#   force = true