global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'puomemo-api'
    static_configs:
      - targets: ['api:8000']
    metrics_path: '/metrics'
    
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
      
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:9187']
      
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:9121']