theme: jekyll-theme-minimal
title: PUO Memo MCP
description: Official documentation for PUO Memo Model Context Protocol server
logo: /assets/logo.png
show_downloads: true
google_analytics: 

navigation:
  - title: Home
    url: /
  - title: Installation
    url: /installation
  - title: Configuration
    url: /configuration
  - title: API Reference
    url: /api-reference
  - title: Examples
    url: /examples
  - title: GitHub
    url: https://github.com/coladapo/puo-memo-mcp