name: CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read
  security-events: write
  actions: read

env:
  PYTHON_VERSION: '3.11'
  NODE_VERSION: '18'

jobs:
  # Linting and code quality
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 black isort mypy pylint
          pip install -r requirements.txt
      
      - name: Run Black formatter check
        run: black --check src/ || echo "Black formatting check skipped"
        continue-on-error: true
      
      - name: Run isort import checker
        run: isort --check-only src/ || echo "isort check skipped"
        continue-on-error: true
      
      - name: Run Flake8 linter
        run: flake8 src/ --max-line-length=120 --extend-ignore=E203,W503 || echo "Flake8 check skipped"
        continue-on-error: true
      
      - name: Run MyPy type checker
        run: mypy src/ --ignore-missing-imports
        continue-on-error: true

  # Security scanning
  security:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'
      
      - name: Upload Trivy scan results
        uses: github/codeql-action/upload-sarif@v3
        if: always()
        with:
          sarif_file: 'trivy-results.sarif'
      
      - name: Run Bandit security linter
        run: |
          pip install bandit
          bandit -r src/ -f json -o bandit-report.json
        continue-on-error: true
      
      - name: Upload Bandit results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: bandit-report
          path: bandit-report.json

  # Unit tests
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: test_password
          POSTGRES_USER: test_user
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
      
      redis:
        image: redis:7
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-cov pytest-asyncio pytest-timeout
          pip install -r requirements.txt
      
      - name: Set up test environment
        env:
          DB_HOST: localhost
          DB_PORT: 5432
          DB_NAME: test_db
          DB_USER: test_user
          DB_PASSWORD: test_password
          REDIS_URL: redis://localhost:6379
          JWT_SECRET_KEY: test-secret-key-for-ci-testing-only
          API_KEY: test-api-key
        run: |
          echo "Test environment configured"
      
      - name: Install Node dependencies
        run: npm ci
      
      - name: Run NPM package tests
        run: npm test
        env:
          CI: true
      
      - name: Test MCP functionality (if API available)
        env:
          PUO_MEMO_API_URL: ${{ secrets.PUO_MEMO_API_URL }}
          PUO_MEMO_API_KEY: ${{ secrets.PUO_MEMO_API_KEY }}
        run: |
          if [ -n "$PUO_MEMO_API_KEY" ]; then
            npm run test:mcp
          else
            echo "Skipping MCP tests - no API key provided"
          fi
        continue-on-error: true
      
      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
      
      - name: Upload coverage HTML report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: coverage-report
          path: htmlcov/
          if-no-files-found: ignore

  # Integration tests
  integration-test:
    name: Integration Tests
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      
      - name: Check for docker-compose
        id: check-compose
        run: |
          if [ -f "docker-compose.yml" ] || [ -f "docker-compose.yaml" ]; then
            echo "has_compose=true" >> $GITHUB_OUTPUT
          else
            echo "has_compose=false" >> $GITHUB_OUTPUT
            echo "::warning::No docker-compose file found. Skipping integration tests."
          fi
      
      - name: Start services with docker-compose
        if: steps.check-compose.outputs.has_compose == 'true'
        run: |
          cp .env.example .env || echo "No .env.example found"
          docker-compose up -d
          sleep 30  # Wait for services to start
      
      - name: Check service health
        if: steps.check-compose.outputs.has_compose == 'true'
        run: |
          docker-compose ps
          curl -f http://localhost:8000/health || exit 1
      
      - name: Run integration tests
        if: steps.check-compose.outputs.has_compose == 'true'
        run: |
          pip install pytest requests
          pytest tests/integration/ -v
        continue-on-error: true
      
      - name: Collect docker logs
        if: always() && steps.check-compose.outputs.has_compose == 'true'
        run: |
          docker-compose logs > docker-logs.txt
      
      - name: Upload docker logs
        uses: actions/upload-artifact@v4
        if: always() && steps.check-compose.outputs.has_compose == 'true'
        with:
          name: docker-logs
          path: docker-logs.txt
      
      - name: Stop services
        if: always() && steps.check-compose.outputs.has_compose == 'true'
        run: docker-compose down
      
      - name: Skip integration tests
        if: steps.check-compose.outputs.has_compose != 'true'
        run: echo "::notice::Integration tests skipped - no docker-compose file"

  # Build Docker image
  build:
    name: Build Docker Image
    runs-on: ubuntu-latest
    needs: [lint, test]
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      
      - name: Check Docker credentials
        id: check-docker
        run: |
          if [ -n "${{ secrets.DOCKER_USERNAME }}" ] && [ -n "${{ secrets.DOCKER_TOKEN }}" ]; then
            echo "has_credentials=true" >> $GITHUB_OUTPUT
          else
            echo "has_credentials=false" >> $GITHUB_OUTPUT
            echo "::warning::Docker credentials not configured. Skipping Docker build and push."
          fi
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        if: steps.check-docker.outputs.has_credentials == 'true' && github.event_name != 'pull_request'
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
      
      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: |
            ${{ secrets.DOCKER_USERNAME }}/puo-memo
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,prefix={{branch}}-
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        if: steps.check-docker.outputs.has_credentials == 'true' || github.event_name == 'pull_request'
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ steps.check-docker.outputs.has_credentials == 'true' && github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
      
      - name: Skip Docker build
        if: steps.check-docker.outputs.has_credentials != 'true' && github.event_name != 'pull_request'
        run: echo "::notice::Docker build skipped due to missing credentials"

  # Deploy to staging
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: [build]
    if: github.ref == 'refs/heads/develop'
    environment: staging
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup SSH
        env:
          STAGING_KEY: ${{ secrets.STAGING_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$STAGING_KEY" > ~/.ssh/staging_key
          chmod 600 ~/.ssh/staging_key
          ssh-keyscan -H ${{ secrets.STAGING_HOST }} >> ~/.ssh/known_hosts 2>/dev/null || true
      
      - name: Deploy to staging server
        env:
          STAGING_HOST: ${{ secrets.STAGING_HOST }}
          STAGING_USER: ${{ secrets.STAGING_USER }}
          SSH_KEY_PATH: ~/.ssh/staging_key
        run: |
          export GIT_SSH_COMMAND="ssh -i $SSH_KEY_PATH -o StrictHostKeyChecking=no"
          bash scripts/deploy-staging.sh

  # Deploy to production
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [build, integration-test]
    if: github.ref == 'refs/heads/main'
    environment: production
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup SSH
        env:
          PROD_KEY: ${{ secrets.PROD_SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$PROD_KEY" > ~/.ssh/prod_key
          chmod 600 ~/.ssh/prod_key
          ssh-keyscan -H ${{ secrets.PROD_HOST }} >> ~/.ssh/known_hosts 2>/dev/null || true
      
      - name: Deploy to production
        env:
          PROD_HOST: ${{ secrets.PROD_HOST }}
          PROD_USER: ${{ secrets.PROD_USER }}
          SSH_KEY_PATH: ~/.ssh/prod_key
        run: |
          export GIT_SSH_COMMAND="ssh -i $SSH_KEY_PATH -o StrictHostKeyChecking=no"
          bash scripts/deploy-production.sh

  # Notification
  notify:
    name: Send Notifications
    runs-on: ubuntu-latest
    needs: [lint, security, test, build]
    if: always()
    steps:
      - name: Send Slack notification
        uses: 8398a7/action-slack@v3
        if: always() && env.SLACK_WEBHOOK_URL != ''
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK }}
        with:
          status: ${{ job.status }}
          text: |
            Pipeline finished with status: ${{ job.status }}
            Commit: ${{ github.sha }}
            Author: ${{ github.actor }}