name: Deploy to Render

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
  RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Run tests
        run: |
          python -m pytest tests/ -v
        continue-on-error: true # Don't block deploy for now
        
      - name: Deploy to Render
        run: |
          curl -X POST \
            -H "Authorization: Bearer $RENDER_API_KEY" \
            -H "Content-Type: application/json" \
            -d '{"serviceId": "'$RENDER_SERVICE_ID'", "clearCache": true}' \
            https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys
            
      - name: Wait for deployment
        run: |
          echo "Deployment triggered. Check Render dashboard for status."
          # Could add polling logic here to wait for completion
          
      - name: Health check
        run: |
          sleep 60 # Wait for deployment to complete
          curl -f https://puo-memo-api.onrender.com/health || echo "Health check failed"